# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        /:title

# Setup
title:            Ayrx's Blog
tagline:          'Infosec, technology and more'
description:      'Infosec guy. Python Developer. These are my thoughts.'
url:              http://ayrx.me
baseurl:          /

author:
  name:           'Terry Chia'

paginate:         5

# Custom vars
version:          2.1.0

github:
  profile:        https://github.com/Ayrx

stackexchange:
  profile:        http://security.stackexchange.com/users/10211/terry-chia

gems:
  - jekyll-feed

feed:
  path: atom.xml
